config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    resources :zombies do
  resources :brains
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end
    root to: 'zombies#index'
    
    get '/sexto/cerebros', to: 'brains#index', as: 'brains'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brain.rb
class Brain < ApplicationRecord
    belongs_to :zombie
    
    validates :flavor,presence: true
    validates :iq, numericality: {only_integer: true, message: "solo numeros enteros"}
    
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/zombie.rb
class Zombie < ApplicationRecord
   
    
    has_many :brains, dependent: :destroy
    validates :name, presence: true
    validates :bio, length: { maximum: 10 }
    validates :age, numericality: {only_integer: true, message: "solo numeros enteros"}
    validates :email, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i, message: "formato requerido"}
    mount_uploader :avatar, AvatarUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController
  before_action :set_brain, only: [:show, :edit, :update, :destroy]

  # GET /brains
  # GET /brains.json
  def index
    @brains = Brain.all
  end

  # GET /brains/1
  # GET /brains/1.json
  def show
  end

  # GET /brains/new
  def new
    @brain = Brain.new
  end

  # GET /brains/1/edit
  def edit
  end

  # POST /brains
  # POST /brains.json
  def create
   # @brain = Brain.new(brain_params)
      @zombie= Zombie.find(params{:zombie_id});
      @brain= @zombie_brains.create(brain_params);
      
    respond_to do |format|
      if @brain.save
        format.html { redirect_to @brain, notice: 'Brain was successfully created.' }
        format.json { render :show, status: :created, location: @brain }
      else
        format.html { render :new }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /brains/1
  # PATCH/PUT /brains/1.json
  def update
    respond_to do |format|
      if @brain.update(brain_params)
        format.html { redirect_to @brain, notice: 'Brain was successfully updated.' }
        format.json { render :show, status: :ok, location: @brain }
      else
        format.html { render :edit }
        format.json { render json: @brain.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brains/1
  # DELETE /brains/1.json
  def destroy
    @brain.destroy
    respond_to do |format|
      format.html { redirect_to brains_url, notice: 'Brain was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brain
      @brain = Brain.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brain_params
        params.require(:brain).permit(:flavor,:iq,:fresh,:zombie_id)
    end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_zombie, only: [:show, :edit, :update, :destroy]

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all
    @rotten_zombies=Zombie.where(rotten:true)  
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(zombie_params)

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render :show, status: :created, location: @zombie }
      else
        format.html { render :new }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { render :show, status: :ok, location: @zombie }
      else
        format.html { render :edit }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie.destroy
    respond_to do |format|
      format.html { redirect_to zombies_url, notice: 'Zombie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombie
      @zombie = Zombie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
        params.require(:zombie).permit(:name, :bio, :age,:email,:rotten,:avatar)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/brains_helper.rb
module BrainsHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/brains/_brain.html.erb
<%= div_for brain do %>
<p>
    <strong>
        agregado:
        <%= time_ago_in_words(brain.created_at) %>
    </strong>
    <br>
    <%=brain.flavor %>
</p>
<% end %>

app/views/brains/_form.html.erb
<%= form_for(brain) do |f| %>
  <% if brain.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brain.errors.count, "error") %> prohibited this brain from being saved:</h2>

      <ul>
      <% brain.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="field">
    <%= f.label :Zombie %>
      <%= f.collection_select :zombie_id, Zombie.order(:name),:id,:name,include_blank:true %>
  </div>
  <div class="field">
    <%= f.label :flavor %>
    <%= f.text_field :flavor %>
  </div>
  
  <div class="field">
      <%= f.label :fresh %>
      <%= f.text_field :fresh %>
  </div>
  <div class="field">
      <%= f.label :iq %>
      <%= f.number_field :iq %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
  
<% end %>

app/views/brains/create.js.erb
var new_brain = $("<%= escape_javascript(:render => @brain)%>").hide();
$("#brains").prepend(new_brain);
$("#brain_<%= @brain_id %>").fadeIn("slow");
$("#new_brain")[0].reset();

app/views/brains/edit.html.erb
<h1>Editing Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Show', @brain %> |
<%= link_to 'Back', brains_path %>

app/views/brains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Brains</h1>

<table>
  <thead>
    <tr>
      <th>Flavor</th>
      <th>Iq</th>
      <th>Fresh</th>
      
      <th colspan="3"></th>
    </tr>
    
  </thead>

  <tbody>
    <% @brains.each do |brain| %>
      <tr>
        <td><%= brain.flavor %></td>
        <td><%= brain.iq %></td>
          <td><%= brain.fresh %></td>
        <td>
           <% if brain.fresh %>
            <%=image_tag 'brains/fresh.png',class:'brains_fresh'%>
            <%else%>
            <%=image_tag 'brains/no_fresh.png',class:'brains_fresh'%>
            <%end%>
        </td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/brains/new.html.erb
<h1>New Brain</h1>

<%= render 'form', brain: @brain %>

<%= link_to 'Back', brains_path %>

app/views/brains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flavor:</strong>
  <%= @brain.flavor %>
</p>
<p>
  <strong>Iq:</strong>
  <%= @brain.iq %>
</p>
<p>
  <strong>Fresh:</strong>
    <%= @brain.fresh %>
</p>

<%= link_to 'Edit', edit_brain_path(@brain) %> |
<%= link_to 'Back', brains_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>
    <div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Home Page</li>
      <li>
        <a href="#">Zombies</a>
        <ul class="menu vertical">
          <li><a href="/zombies">List</a></li>
         <li><a href="zombies/new">New</a></li>
        </ul>
      </li>
     
    </ul>
  </div>
 
</div>
      <div class="top-bar-right">
      <% if user_signed_in? %>
          
          <strong>Bienvenido(a) <%= current_user.email %></strong>
          <strong><%= link_to "cerrar sesion", destroy_user_session_path,method: :delete %></strong>
          
          <strong><%= link_to "editar perfil", edit_user_registration_path %></strong>
        
          
          <% else %>
          
          <strong><%=link_to"login", new_user_session_path%></strong>
          
          <strong><%=link_to"Registro", new_user_registration_path%></strong>

          <%end%>
     
      </div>
      
      <% if notice %>
      <p class="alert alert-success"><%= notice %></p><% end %>
      <% if alert %>
      <p class="alert alert-danger"><%=alert%></p>
      <% end %>
      
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    
    <%= yield %>
    
  </body>
</html>

app/views/zombies/_form.html.erb
<%= form_for(zombie) do |f| %>
  <% if zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% zombie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="container">
    <div class="row">
<div class="large-6 column">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :bio %>
    <%= f.text_area :bio %>
  </div>
</div>
    <div class="large-6 column">
  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>
  
   <div class="field">
       <%= f.label :email %>
       <%= f.text_field :email %>
  </div>
  
   <div class="field">
       <%= f.label :rotten %>
       <%= f.check_box :rotten %>
  </div>
   <div class="field">
       <%= f.label :avatar %>
       <%= f.file_field :avatar %>
       
  </div>
        </div>
    </div> 
  <div class="actions">
    <%= f.submit class: "button", type: "submit" %>
  </div>
</div>

<% end %>

app/views/zombies/edit.html.erb
<h1>Editing Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Zombies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Age</th>
      <th>Email</th>
      <th>Rotten</th>
      <th>Avatar</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <% @rotten_zombies.each do |zombie| %>
      <tr>
        <td><%= zombie.name %></td>
        <td><%= zombie.bio %></td>
        <td><%= zombie.age %></td>
          <td><%= zombie.email %></td>
      
          <td><%= zombie.rotten ? "yes" : "no" %></td>
                    <td><%=image_tag zombie.avatar, :width=> "150px" %></td>

        <td><%= link_to 'Show', zombie, :class=> 'button',:style=>'color:#FFFFFF;' %></td>
        <td><%= link_to 'Edit', edit_zombie_path(zombie), :class=> 'button secondary',:style=>'color:#FFFFFF;' %></td>
        <td><%= link_to 'Destroy', zombie, :class=> 'button alert', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zombie', new_zombie_path %>

app/views/zombies/new.html.erb
<h1>New Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<div class="show">
<div class="container"> 
<div class="row">
    <div class="large-6 columns">
        <%=image_tag @zombie.avatar, class:"avatar"%>
    </div>
<div class="large-6 columns">
<table class="table table-reflow">
  <thead>
    <tr>
      
      <th>Age</th>
      <th>Email</th>
      <th>Rotten</th>
    </tr>
  </thead>
  <tbody>
    <tr> 
      <td><%= @zombie.age %></td>
      <td><%=@zombie.email%></td>
      <td><%=@zombie.rotten%></td>
    </tr>
</table> 
</div> 
 </div>
<div id="brains">
    <%= render :partial=>@zombie.brains.reverse%>
</div>

<%= form_for([@zombie, Brain.new],remote:true)do|f|%>
  <form class="formulario">
    <div class="field form-group">
        <%= f.label :flavor%>
        <%= f.text_field :flavor,class:"form-control"%>
    </div>
    <div class="field form-group">
        <%= f.label :iq%>
        <%= f.number_field :iq,class:"form-control"%>
    </div>
    <div class="field form-group">
        <%= f.label :fresh%>
        <%= f.check_box :fresh,class:"form-control"%>
    </div>
    <div class="action">
        <%= f.submit "Add brain",class:"btn btn-primary"%>
    </div>
    </form>
</div>
</div>       
    <%end%>
<br>    
<%= link_to 'Edit', edit_zombie_path(@zombie),class:"btn btn-info" %> |
<%= link_to 'Back', zombies_path,class:"btn btn-info" %>